# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this Jupyter notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to deliver the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the Jupyter notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - Remember to avoid explicit Python loops!  
4. Quality and correctness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 points

In [2]:
import matplotlib.pylab as plt

**1. Import the NumPy package under the name np**

In [3]:
import numpy as np

**2. Print the NumPy version and the configuration**

In [5]:
# Print the NumPy version
print("NumPy version:", np.__version__)

# Print the NumPy configuration
print("NumPy configuration:")
print(np.__config__.show())

NumPy version: 1.21.2
NumPy configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H',

**3. Create a 1D array of zeros of size 10 of type float32**

In [7]:
# Generate array according to the specifications
q3 = np.zeros((10), dtype='float32')

# Print the array and type
print("Array:", q3)
print("Array type:", q3.dtype)

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array type: float32


**4. Print the memory size of the array below**

In [8]:
Z = np.zeros((32, 12))

# Obtain the memory size of the array in bytes
print("Array memory size: {} bytes".format(Z.nbytes))

Array memory size: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [9]:
# Generate a 1D array containing values 10 to 58
q5 = np.arange(10, 59)

print("1D array containing values [10, 58]:\n", q5)

1D array containing values [10, 58]:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [10]:
a = np.arange(10)

# Reverse the order of the array (note that this is a shallow copy of a)
a_reversed = a[::-1]

print("Original array:", a)
print("Reversed array:", a_reversed)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [11]:
# Generate a 1D array with values of 0 to 8 and reshape it to be 3x3 
q7 = np.arange(9).reshape(3, 3)

print("3x3 matrix containing values [0, 8]:\n", q7)

3x3 matrix containing values [0, 8]:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [12]:
# Generate a 3x3 identity matrix
q8 = np.identity(3)

print("3x3 identity matrix:\n", q8)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [15]:
Z = np.random.random((10, 11))

# Obtain the maximum value of each column
Z_max_col = Z.max(axis=0)

print("Original array:\n", Z)
print("Maximum value of each column:\n", Z_max_col)

Original array:
 [[0.65296179 0.70253911 0.0626164  0.28759289 0.93414729 0.41015087
  0.55241806 0.0921523  0.04397593 0.87382534 0.22638678]
 [0.00619794 0.07662119 0.04994382 0.28288395 0.56649656 0.55918482
  0.67807924 0.47946287 0.75587559 0.42900009 0.54925352]
 [0.2884477  0.4773482  0.28924845 0.02246314 0.89390148 0.76284022
  0.3482918  0.45548421 0.02518729 0.35404836 0.21736907]
 [0.33771898 0.30894756 0.89276954 0.1249847  0.81626123 0.39289949
  0.97740293 0.1791315  0.09478504 0.09329273 0.07400977]
 [0.57424082 0.49862511 0.45478145 0.68148129 0.02045496 0.36168115
  0.35216799 0.31407426 0.49437544 0.9488993  0.24444624]
 [0.93859742 0.92655315 0.46662127 0.73217781 0.69102403 0.69541992
  0.88214449 0.94843122 0.89027882 0.18065845 0.81243287]
 [0.88855909 0.02376726 0.90632262 0.04813067 0.9825794  0.99905197
  0.46116816 0.45659067 0.51052761 0.14057126 0.08232881]
 [0.01842801 0.58363049 0.70521347 0.28765084 0.76545705 0.80676378
  0.94375916 0.67133764 0.5580673

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and column) and 0s everywhere else**

In [16]:
# Generate a 7x7 matrix of ones
q10 = np.ones((7, 7))

# Fill the inner elements with zeros by specifying the proper indices
q10[1:-1, 1:-1] = 0

print("7x7 array with ones on the border and zeros everywhere else:\n", q10)

7x7 array with ones on the border and zeros everywhere else:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [17]:
Z = np.ones((5, 5))

# Pad the array with zeros
Z_padded = np.pad(Z, 1)

print("Original array:\n", Z)
print("Padded array:\n", Z_padded)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Padded array:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [18]:
Z = np.random.uniform(0, 10, 10)

# Take the integer part of each element in the array
Z_int = Z.astype(int)

print("Original array:\n", Z)
print("Integer array:\n", Z_int)

Original array:
 [6.48345005 4.18976055 3.60958085 3.43701423 9.16451057 3.93171822
 9.50233574 9.67684513 3.51788483 2.95886586]
Integer array:
 [6 4 3 3 9 3 9 9 3 2]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0, 1, 2, 3, 4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [19]:
# Generate an array with rows containing values ranging from 0 to 4
q13 = np.tile([0, 1, 2, 3, 4], (5, 1))

print("5x5 matrix with rows containing values [0, 4]:\n", q13)

5x5 matrix with rows containing values [0, 4]:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [20]:
# Generate an array ranging from 0 to 1, slicing the array to exclude 0 and setting the linspace() 'endpoint' argument to 'False' to exclude 1
q14 = np.linspace(0, 1, 11, endpoint=False)[1:]

print("Array of size 10 containing values (0, 1)\n", q14)

Array of size 10 containing values (0, 1)
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [21]:
# Generate randomized array of size 10
q15_random = np.random.rand(10)

# Sort the randomized array
q15_sorted = np.sort(q15_random)

print("Random array:\n", q15_random)
print("Sorted array:\n", q15_sorted)

Random array:
 [0.81447031 0.71302819 0.49183889 0.00135412 0.66316272 0.30304503
 0.31601591 0.94876119 0.04822373 0.61005354]
Sorted array:
 [0.00135412 0.04822373 0.30304503 0.31601591 0.49183889 0.61005354
 0.66316272 0.71302819 0.81447031 0.94876119]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [22]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]

# Convert Cartesian coordinates to polar coordinates using the corresponding formula for the radius (R) and angle (T)
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)

print("Cartesian coordinates:")
print("X =", X)
print("Y =", Y)

print("\nPolar coordinates:")
print("R =", R)
print("T (radians) =", T)

Cartesian coordinates:
X = [0.393856   0.60503272 0.22120474 0.5304417  0.24292175 0.02644751
 0.75854582 0.43693074 0.11735347 0.38419697]
Y = [0.45205273 0.44696302 0.41948273 0.91586954 0.71488568 0.01170864
 0.60843453 0.98110115 0.79818446 0.38604107]

Polar coordinates:
R = [0.59956169 0.75222373 0.47423338 1.05838812 0.75503146 0.02892339
 0.97241161 1.07399625 0.80676531 0.54464211]
T (radians) = [0.8540878  0.6362569  1.08552655 1.04583584 1.24323259 0.416777
 0.67602407 1.15181832 1.42481669 0.78779236]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [23]:
# Generate randomized array of size 10
q17_random = np.random.rand(10)

# Replace maximum value with 0 using a boolean mask
q17_max_replaced = q17_random.copy()
q17_max_replaced[q17_random.argmax()] = 0

print("Randomized array:\n", q17_random)
print("Max value replaced array:\n", q17_max_replaced)

Randomized array:
 [0.44647555 0.42199617 0.81494238 0.01041374 0.04867302 0.34145548
 0.49775378 0.99831982 0.18164325 0.12745329]
Max value replaced array:
 [0.44647555 0.42199617 0.81494238 0.01041374 0.04867302 0.34145548
 0.49775378 0.         0.18164325 0.12745329]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [27]:
Z = np.random.uniform(0, 1, 10)
z = 0.5

# Retrive the nearest value by obtaining the index of the element in Z with the smallest difference to z
q18 = Z[np.abs(Z - z).argmin()]

print("Original array:\n", Z)
print("Value of z:", z)
print("Nearest value to z:", q18)

Original array:
 [0.65832446 0.97326457 0.17917199 0.26663026 0.98546053 0.27395666
 0.7469951  0.49410156 0.37739043 0.05686106]
Value of z: 0.5
Nearest value to z: 0.4941015603327287


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [28]:
Z = np.arange(6)[:0:-1]

# Generate a zeros array of appropriate length
Z_interleaved = np.zeros(4 * ((len(Z) - 1)) + 1, dtype=int)

# Replace every fourth element with an element in Z
Z_interleaved[::4] = Z

print("Original array:\n", Z)
print("Interleaved array:\n", Z_interleaved)

Original array:
 [5 4 3 2 1]
Interleaved array:
 [5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5, 5, 3), how to mulitply it element-wise by an array with dimensions (5, 5) - i.e., (5, 5, 0)$\times$(5, 5), (5, 5, 1)$\times$(5, 5), (5, 5, 2)$\times$(5, 5)**

In [29]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))

# Add third dimension to B and multiply with A
q20 = np.multiply(A, B.reshape(5, 5, 1))

print("Element-wise product:\n", q20)
print("\nShape of result:", q20.shape)

Element-wise product:
 [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]

Shape of result: (5, 5, 3)


**21. Swap the first and second rows of the 2D array below**

In [30]:
W = np.arange(30).reshape(6, 5)
print("Original array:\n", W)
print()

# Use advanced slicing to swap rows
W[[0, 1], :] = W[[1, 0], :]

print("Array with swapped rows:\n", W)

Original array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Array with swapped rows:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding box
that encloses all non-zero elements in the input array**

**Tip:** Search for the functions non-zero and where in the NumPy documentation.

<img src="./bbox.png" width="150" /> 

In [31]:
def bbox(img):
    # Obtain the row and column indices of the non-zero elements as a tuple
    bb_idx = np.nonzero(img)

    # Retrieve the minimum and maximum row/column indices to get the minimum bounding-box
    r1 = bb_idx[0].min()
    c1 = bb_idx[1].min()
    r2 = bb_idx[0].max()
    c2 = bb_idx[1].max()
    
    return (r1, c1), (r2, c2)


from PIL import Image

img = np.array(Image.open('./bin_image.png').convert('L')) > 0
print("Minimum bounding box:", bbox(img))

Minimum bounding box: ((29, 50), (342, 431))


**23. Write a function to compute the average over a sliding window of length N over a 1D array**

*Example:* [1, 2, 3, 4, 5, 6, 7, 8, 9], N = 3 -> [2, 5, 8]

In [32]:
def moving_average(x, N=3):
    # Pad array with zeros if the size of array x is not a multiple of N
    if x.size % N != 0:
        x = np.pad(x, (0, x.size % N))
    
    # Reshape the array to be 2D where each row has N elements and calculate the average of each
    x = x.reshape(int(x.size / N), N)
    x = x.sum(axis=1) / N

    # Flatten back to a 1D array
    x = x.flatten()

    return x


a = np.arange(30)
N = 3
print("Original array:", a)
print("Sliding window moving average:", moving_average(a, N))

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Sliding window moving average: [ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3, 2, 4] -> D = [0, 0, 0, 1, 1, 2, 2, 2, 2]

*Tip:* Consider using the NumPy repeat function

In [33]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
print("bincount array C =", C)

# Repeat the elements in A using the values of C
A = np.repeat(np.arange(C.size), C)

print("\nInverse bincount array A =", A)
print("Verify bincount:", np.bincount(A))

bincount array C = [0 2 1 1 2 0 1]

Inverse bincount array A = [1 1 2 3 4 4 6]
Verify bincount: [0 2 1 1 2 0 1]


**25. Find the most frequent value in the array below?**

In [49]:
Z = np.random.randint(0, 10, 50)

# Record the instances of each number in the array
Z_counts = np.bincount(Z)

# Retrive the number with the maximum number of instances
Z_max = np.argmax(Z_counts)

print("Original array:\n", Z)
print("Array value counts:", Z_counts)
print("Most frequent array value:", Z_max)

Original array:
 [6 5 6 3 7 9 3 1 7 5 5 7 5 4 2 8 2 9 9 0 5 1 9 1 0 1 5 9 2 4 4 8 5 9 7 1 6
 7 1 1 1 3 4 4 2 5 1 3 4 0]
Array value counts: [3 9 4 4 6 8 3 5 2 6]
Most frequent array value: 1


**26. Write a function to return the n largest values of an array** 

In [50]:
def nlargest(a, n=5):
    # Sort the array in ascending order
    a.sort()

    # Reverse array to descending order and return the first n elements
    return a[::-1][0:n]


Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print("n largest values of the array:", nlargest(Z, n))    

n largest values of the array: [9999 9998 9997 9996 9995]


## Team Contributions

All team members worked on the Assignment 1 Jupyter notebook individually and met together to discuss and choose the best answer for each question.

| Team Member      | Consensus Score |
| ---------------- | --------------- |
| Brandon Attai    | 3               |
| Tahsin Chowdhury | 3               |
| Kelten Falez     | 3               |
| Timothy Mok      | 3               |
| Aron Saengchan   | 3               |
| Yong Jun Zhu     | 3               |