# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to deliver the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correctness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 points

In [3]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [4]:
import numpy as np

**2. Print the numpy version and the configuration**

In [5]:
# Print the NumPy version
print("NumPy version:", np.__version__)

# Print the NumPy configuration
print("NumPy configuration:")
print(np.__config__.show())

NumPy version: 1.21.2
NumPy configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H',

**3. Create a 1D array of zeros of size 10 of type float32**

In [6]:
# Generate array according to the specifications
q3 = np.zeros((10), dtype='float32')

# Printing the array and type
print("Array:", q3)
print("Type:", q3.dtype)

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Type: float32


**4. Print the memory size of the array below**

In [7]:
Z = np.zeros((32, 12))

# Obtain the memory size of the array by using the 'nbytes' attribute
print("Array memory size: {} bytes".format(Z.nbytes))

Array memory size: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [8]:
# Generate a 1D array containing values 10 to 58
q5 = np.arange(10, 59)

print("1D array containing values [10, 58]:\n", q5)

1D array containing values [10, 58]:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [9]:
a = np.arange(10)

# Reverse the order of the array (note that this is a shallow copy of a)
a_reversed = a[::-1]

print("Original array:", a)
print("Reversed array:", a_reversed)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [10]:
# Generate a 1D array with values of 0 to 8 and reshape it to be 3x3 
q7 = np.arange(9).reshape(3, 3)

print("3x3 array containing values [0, 8]:\n", q7)

3x3 array containing values [0, 8]:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [11]:
# Generate a 3x3 identity matrix
q8 = np.identity(3)

print("3x3 identity matrix:\n", q8)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [12]:
Z = np.random.random((10,11))

# Obtain the max value of each column
Z_max_col = Z.max(axis=0)

print("Maximum value of each column:\n", Z_max_col)

Maximum value of each column:
 [0.71818134 0.9519471  0.93754752 0.74977056 0.97008057 0.79244627
 0.83446611 0.74871567 0.93658422 0.86620184 0.98350357]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [13]:
# Generate a 7x7 matrix of ones
q10 = np.ones((7, 7))

# Fill the inner elements with zeros by specifying the proper indices
q10[1:-1, 1:-1] = 0

print("7x7 array with ones on the border and zeros everywhere else:\n", q10)

7x7 array with ones on the border and zeros everywhere else:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [14]:
Z = np.ones((5, 5))

# Pad the array with zeros
Z_padded = np.pad(Z, (1, 1), mode='constant')

print("Original array:\n", Z)
print("Padded array:\n", Z_padded)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Padded array:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [15]:
Z = np.random.uniform(0, 10, 10)

# Take the integer part of each element in the array
Z_int = Z.astype(int)

print("Original array:\n", Z)
print("Integer array:\n", Z_int)

Original array:
 [9.26636575 3.77301499 3.0591517  0.40060605 0.90519636 3.94435407
 2.12518588 7.23853491 1.08583106 6.58554815]
Integer array:
 [9 3 3 0 0 3 2 7 1 6]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0, 1, 2, 3, 4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [16]:
# Generate an array with rows containing values from 0 to 5
q13 = np.tile([0, 1, 2, 3, 4, 5], (5, 1))

print("5x5 matrix with rows ranging from 0 to 5:\n", q13)

5x5 matrix with rows ranging from 0 to 5:
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [17]:
# Generate an array ranging from 0 to 1, then slice array to exclude 0 and set linspace() endpoint argument to 'False' to exclude 1
q14 = np.linspace(0, 1, 11, endpoint=False)[1:]

print(q14)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [18]:
# Generate randomized array of size 10
q15_random = np.random.rand(10)

# Sort the randomized array
q15_sorted = np.sort(q15_random)

print("Random array:\n", q15_random)
print("Sorted array:\n", q15_sorted)

Random array:
 [0.37341214 0.14721701 0.11579707 0.11019488 0.82704975 0.38835621
 0.40544592 0.16422442 0.20104908 0.17361977]
Sorted array:
 [0.11019488 0.11579707 0.14721701 0.16422442 0.17361977 0.20104908
 0.37341214 0.38835621 0.40544592 0.82704975]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [19]:
Z = np.random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]

# Convert Cartesian coordinates to polar coordinates using the corresponding formula for radius (R) and angle (T)
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)

print("Cartesian coordinates:")
print("X =", X)
print("Y =", Y)

print("\nPolar coordinates:")
print("R =", R)
print("T (radians) =", T)



Cartesian coordinates:
X = [0.05175005 0.48430893 0.78443653 0.82939047 0.27297735 0.0548432
 0.46071557 0.92957438 0.68378861 0.6047638 ]
Y = [0.02966453 0.37652856 0.16956792 0.78771025 0.31975387 0.98131054
 0.50168395 0.15675182 0.79562655 0.59731635]

Polar coordinates:
R = [0.05964941 0.61345652 0.80255464 1.14384264 0.42042737 0.98284188
 0.68113554 0.94269808 1.04908936 0.85001534]
T (radians) = [0.52050092 0.66084222 0.21288966 0.75962921 0.86415187 1.51496669
 0.82794146 0.16705593 0.8608507  0.77920277]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [20]:
# Generate randomized array of size 10
q17_randomized = np.random.rand(10)

# Replace maximum value with 0 using a boolean mask
q17_max_replaced = q17_randomized.copy()
q17_max_replaced[q17_randomized == q17_randomized.max()] = 0

print("Randomized array:\n", q17_randomized)
print("Max value replaced array:\n", q17_max_replaced)


Randomized array:
 [0.39415231 0.57195938 0.3847846  0.73046161 0.95634619 0.16444477
 0.57501276 0.44244876 0.48458339 0.50788394]
Max value replaced array:
 [0.39415231 0.57195938 0.3847846  0.73046161 0.         0.16444477
 0.57501276 0.44244876 0.48458339 0.50788394]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [21]:
Z = np.random.uniform(0, 1, 10)
z = 0.5

# Retrive the nearest value by obtainign the index of the element in Z with the smallest difference to z
q18 = Z[np.abs(Z - z).argmin()]

print("Orginal array:\n", Z)
print("Nearest value to z = 0.5:\n", q18)

Orginal array:
 [0.66911007 0.62539982 0.71991741 0.91972217 0.1430565  0.05302498
 0.7994744  0.86488647 0.27931827 0.97453054]
Nearest value to z = 0.5:
 0.6253998178451811


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [22]:
Z = np.arange(6)[:0:-1]

# Generate zeros array of appropriate length
q19 = np.zeros(4 * ((len(Z) - 1)) + 1, dtype=int)

# Replace every fourth element with an element in Z
q19[::4] = Z

print("Original array:\n", Z)
print("Interleaved array:\n", q19)

Original array:
 [5 4 3 2 1]
Interleaved array:
 [5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5, 5, 3), how to mulitply it element-wise by an array with dimensions (5, 5) - i.e., (5, 5, 0)$\times$(5, 5), (5, 5, 1)$\times$(5, 5), (5, 5, 2)$\times$(5, 5)**

In [23]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))

# Add third dimension to B and multiply with A
q20 = A * B.reshape(5, 5, 1)

print("Element-wise product:\n", q20)

Element-wise product:
 [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [24]:
W = np.arange(30).reshape(6, 5)
print("Array before swapping rows:\n", W)
print()

# Use advanced slicing to swap rows
W[[0, 1], :] = W[[1, 0], :]

print("Array after swapping rows:\n", W)

Array before swapping rows:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

Array after swapping rows:
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** Search for the functions non-zero and where in the NumPy documentation.


<img src="./bbox.png" width="150" /> 

In [107]:
def bbox(img):
    # Obtain the row and column indices of the non-zero elements as a tuple
    bb_idx = np.nonzero(img)

    # Retrieve the minimum and maximum rows and columns indices to get the minimal bounding-box
    r1 = bb_idx[0].min()
    c1 = bb_idx[1].min()
    r2 = bb_idx[0].max()
    c2 = bb_idx[1].max()
    
    return (r1, c1), (r2, c2)


from PIL import Image

img = np.array(Image.open('./bin_image.png').convert('L')) > 0
print("Minimal bounding-box:", bbox(img))

Minimal bounding-box: ((29, 50), (342, 431))


**23. Write a function to compute the average over a sliding window of length N over a 1D array**

*Example:* [1, 2, 3, 4, 5, 6, 7, 8, 9], N = 3 -> [2, 5, 8]

In [106]:
def moving_average(x, N=3):
    # Reshape the array to have multiple rows for each N element and take the average of each row
    return np.mean(x.reshape(-1, 3), axis=1)


a = np.arange(30)
N = 3
print("Sliding window moving average:", moving_average(a, N))

Sliding window moving average: [ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3, 2, 4] -> D = [0, 0, 0, 1, 1, 2, 2, 2, 2]

*Tip:* Consider using the NumPy repeat function

In [100]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
print("bincount array C =", C)

# Repeat the elements in A using the values of C
A = np.repeat(np.arange(C.size), C)

print("Inverse bincount array A =", A)

bincount array C = [0 2 1 1 2 0 1]
Inverse bincount array A = [1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [69]:
Z = np.random.randint(0, 10, 50)

# Record the instances of each number in the array
counts = np.bincount(Z)

# Retrive the number with the maximum number of instances
q25 = np.argmax(counts)

print("Most frequent array value:", q25)

Most frequent array value: 4


**26. Write a function to return the n largest values of an array** 

In [95]:
def nlargest(a, n=5):
    # Sort the array in ascending order, reverse array to descending order, and return the first n elements
    return a.sort()[::-1][0:n]

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print("n largest values of the array:", nlargest(Z, n))    

n largest values of the array: [9999 9998 9997 9996 9995]
