# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [ ]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [12]:
print("Numpy version: " + np.__version__)
print(np.show_config())

Numpy version: 1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kelten/anaconda3/envs/ensf-ml\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)

**3. Create a 1D array of zeros of size 10 of type float32**

In [141]:
zero_array = np.zeros((10), dtype= 'float32')
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [140]:
Z = np.zeros((32,12))
# Include your solution below
print("%d bytes" % (Z.size * Z.itemsize))

3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [139]:
y = np.arange(10, 59)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [28]:
a = np.arange(10)
# Include your solution below
a = a[:: -1]

**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [126]:
q_7 = np.arange(0, 9).reshape(3,3)
print(q_7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [127]:
id_matrix = np.identity(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [128]:
Z = np.random.random((10,11))
# Include your solution below
np.max(Z, axis=0)

array([0.99390182, 0.93229898, 0.82809245, 0.96327356, 0.98566416,
       0.92445031, 0.96442901, 0.88895555, 0.89599943, 0.96156243,
       0.82961279])

**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [130]:
zer = np.zeros((5,5))
out = np.ones((7,7))
out[1: -1, 1: -1] = zer
print(out)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [131]:
Z = np.ones((5,5))
# Include your solution below
np.pad(Z, (1,3), 'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**12. Extract the integer part of the random array of positive numbers below**

In [133]:
Z = np.random.uniform(0,10,10)
# Include your solution below
Z_int = np.rint(Z).flatten()
print(Z_int)

[8. 9. 5. 0. 7. 7. 4. 5. 4. 8.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [135]:
a = np.array([0, 1, 2, 3 ,4])
a = np.tile(a, (5, 1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [136]:
vec = np.linspace(0, 1, num = 11, endpoint=False)[1:]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [137]:
rand_vec = np.random.random(10)
rand_vec.sort()
print(rand_vec)

[0.20168301 0.25462293 0.30239912 0.37410916 0.38133138 0.39909508
 0.45892914 0.62586292 0.77598261 0.94213224]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [119]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(f"Cartesian Coords\n (", X, ", ", Y, ")\n")
print(f"Polar Coords\n (", R, ", ", T, ")")

Cartesian Coords
 ( [0.28195891 0.07142955 0.29471805 0.49720597 0.84574687 0.6045081
 0.33176116 0.84935093 0.66139945 0.95805795] ,  [0.26608395 0.00343954 0.0409687  0.09499523 0.55505076 0.04622358
 0.49548015 0.2745077  0.66137337 0.10090947] )

Polar Coords
 ( [0.38768737 0.07151231 0.29755195 0.50619944 1.01161707 0.60627276
 0.59629359 0.89260936 0.93534163 0.96335754] ,  [0.75643962 0.04811569 0.13812466 0.18878299 0.58078063 0.07631628
 0.9807829  0.31260031 0.78537845 0.10494018] )


**17. Create random vector of size 10 and replace the maximum value by 0**

In [109]:
rand_vec = np.random.random(10)
print("Original vector:\n" , rand_vec)
rand_vec[rand_vec.argmax()] = 0
print("\nSorted vector:\n", rand_vec)

Original vector:
 [0.50309799 0.94037296 0.19149016 0.62835382 0.48720105 0.05634706
 0.50261416 0.38693878 0.10553482 0.55460345]

Sorted vector:
 [0.50309799 0.         0.19149016 0.62835382 0.48720105 0.05634706
 0.50261416 0.38693878 0.10553482 0.55460345]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [124]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(Z)
# Include your solution below
indx = (np.abs(Z - z)).argmin()
Z[indx]
print("\n", Z[indx])

[0.249261   0.54511953 0.40331579 0.92531634 0.75825609 0.54437888
 0.05523944 0.13384941 0.05444416 0.26182456]

 0.5443788813567447


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [143]:
Z = np.arange(5)[::-1]
# Include your solution below
print(Z)
Z_consec = np.zeros(len(Z) + (len(Z) - 1) * 3)
Z_consec[::3+1] = Z
print(Z_consec)

[4 3 2 1 0]
[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [148]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
print(A)
print(B)

arr = (A.transpose() * B.transpose().transpose())
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [153]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below
W[[0, 1]] = W[[1, 0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [202]:
def moving_average(x,N = 3):
    #define your function here
    z = np.cumsum(x)
    z[N:] = z[N:] - z[:-N]
    return z[N- 1::N] / N

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [208]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
np.repeat(np.arange(C.size), C)

[0 2 1 1 2 0 1]


array([1, 1, 2, 3, 4, 4, 6])

**25. Find the most frequent value in the array below?**

In [211]:
Z = np.random.randint(0,10,50)
# Include your solution below
cts = np.bincount(Z)
print(np.argmax(cts))

4


**26. Write a function to return the n largest values of an array** 

In [214]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return np.argsort(a)[::-1][:n]

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

[5645  212 4219 3825 4980]
