# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to deliver the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correctness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 points

In [2]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

In [4]:
# Print the NumPy version
print("NumPy version:", np.__version__)

# Print the NumPy configuration
print("NumPy configuration:")
print(np.__config__.show())

NumPy version: 1.21.2
NumPy configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/acsaeng/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H',

**3. Create a 1D array of zeros of size 10 of type float32**

In [5]:
# Generate array according to the specifications
q3 = np.zeros((10), dtype='float32')

# Printing the array and type
print("Array:", q3)
print("Type:", q3.dtype)

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Type: float32


**4. Print the memory size of the array below**

In [6]:
Z = np.zeros((32, 12))

# Obtain the memory size of the array by using the 'nbytes' attribute
print("Array memory size: {} bytes".format(Z.nbytes))

Array memory size: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [7]:
# Generate a 1D array containing values 10 to 58
q5 = np.arange(10, 59)

print("1D array containing values [10, 58]:\n", q5)

1D array containing values [10, 58]:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [8]:
a = np.arange(10)

# Reverse the order of the array (note that this is a shallow copy of a)
a_reversed = a[::-1]

print("Original array:", a)
print("Reversed array:", a_reversed)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [9]:
# Generate a 1D array with values of 0 to 8 and reshape it to be 3x3 
q7 = np.arange(9).reshape(3, 3)

print("3x3 array containing values [0, 8]:\n", q7)

3x3 array containing values [0, 8]:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [10]:
# Generate a 3x3 identity matrix
q8 = np.identity(3)

print("3x3 identity matrix:\n", q8)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [11]:
Z = np.random.random((10,11))

# Obtain the max value of each column
Z_max_col = Z.max(axis=0)

print("Maximum value of each column:\n", Z_max_col)

Maximum value of each column:
 [0.98746222 0.70106228 0.93088757 0.90517161 0.94281133 0.81919897
 0.95739613 0.94979088 0.99346689 0.83064868 0.88409961]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [21]:
# Generate a 7x7 matrix of ones
q10 = np.ones((7, 7))

# Fill the inner elements with zeros by specifying the proper indices
q10[1:-1, 1:-1] = 0

print("7x7 array with ones on the border and zeros everywhere else:\n", q10)

7x7 array with ones on the border and zeros everywhere else:
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [13]:
Z = np.ones((5, 5))

# Pad the array with zeros
Z_padded = np.pad(Z, (1, 1), mode='constant')

print("Original array:\n", Z)
print("Padded array:\n", Z_padded)

Original array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Padded array:
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [18]:
Z = np.random.uniform(0, 10, 10)

# Take the integer part of each element in the array
Z_int = Z.astype(int)

print("Original array:\n", Z)
print("Integer array:\n", Z_int)

Original array:
 [4.11045999 1.63095527 9.28998275 5.01037561 0.90409334 9.50059937
 0.74122459 0.70628516 0.19734202 3.37281426]
Integer array:
 [4 1 9 5 0 9 0 0 0 3]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0, 1, 2, 3, 4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [25]:
# Generate an array with rows containing values from 0 to 5
q13 = np.tile([0, 1, 2, 3, 4, 5], (5, 1))

print("5x5 matrix with rows ranging from 0 to 5:\n", q13)

5x5 matrix with rows ranging from 0 to 5:
 [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [35]:
# Generate an array ranging from 0 to 1, then slice array to exclude 0 and set linspace() endpoint argument to 'False' to exclude 1
q14 = np.linspace(0, 1, 11, endpoint=False)[1:]

print(q14)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [41]:
# Generate randomized array of size 10
q15_random = np.random.rand(10)

# Sort the randomized array
q15_sorted = np.sort(q15_random)

print("Random array:\n", q15_random)
print("Sorted array:\n", q15_sorted)

Random array:
 [0.51159776 0.46417068 0.14967886 0.51597706 0.96254319 0.91344831
 0.59687375 0.62295674 0.97137867 0.38330855]
Sorted array:
 [0.14967886 0.38330855 0.46417068 0.51159776 0.51597706 0.59687375
 0.62295674 0.91344831 0.96254319 0.97137867]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [59]:
Z = np.random.random((10,2))
X, Y = Z[:, 0], Z[:, 1]

# Convert Cartesian coordinates to polar coordinates using the corresponding formula for radius (R) and angle (T)
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)

print("Cartesian coordinates:")
print("X =", X)
print("Y =", Y)

print("\nPolar coordinates:")
print("R =", R)
print("T (radians) =", T)



Cartesian coordinates:
X = [0.60342546 0.88570147 0.15789264 0.39801277 0.8319341  0.66887522
 0.44608848 0.51932281 0.45937831 0.04074953]
Y = [0.42254835 0.64136056 0.18437179 0.82822784 0.43204651 0.12216442
 0.76538611 0.02293876 0.32198844 0.81797307]

Polar coordinates:
R = [0.73666097 1.09353119 0.24274069 0.91889908 0.93743189 0.67993985
 0.8858955  0.51982918 0.56098573 0.81898747]
T (radians) = [0.61089336 0.62673589 0.86260897 1.12282171 0.47899003 0.18065042
 1.04309897 0.04414183 0.61134459 1.52101979]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [67]:
# Generate randomized array of size 10
q17_randomized = np.random.rand(10)

# Replace maximum value with 0 using a boolean mask
q17_max_replaced = q17_randomized.copy()
q17_max_replaced[q17_randomized == q17_randomized.max()] = 0

print("Randomized array:\n", q17_randomized)
print("Max value replaced array:\n", q17_max_replaced)


Randomized array:
 [0.22752912 0.11706537 0.12786778 0.64605395 0.28395647 0.2672393
 0.35393255 0.6487586  0.23962963 0.24202086]
Max value replaced array:
 [0.22752912 0.11706537 0.12786778 0.64605395 0.28395647 0.2672393
 0.35393255 0.         0.23962963 0.24202086]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [72]:
Z = np.random.uniform(0, 1, 10)
z = 0.5

# Retrive the nearest value by obtainign the index of the element in Z with the smallest difference to z
q18 = Z[np.abs(Z - z).argmin()]

print("Orginal array:\n", Z)
print("Nearest value to z = 0.5:\n", q18)



Orginal array:
 [0.39717345 0.69459253 0.65275264 0.31399238 0.68480328 0.17438572
 0.85790814 0.82279469 0.92980935 0.59214456]
Nearest value to z = 0.5:
 0.5921445598615366


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [147]:
Z = np.arange(6)[:0:-1]

# Generate zeros array of appropriate length
q19 = np.zeros(4 * ((len(Z) - 1)) + 1, dtype=int)

# Replace every fourth element with an element in Z
q19[::4] = Z

print("Original array:\n", Z)
print("Interleaved array:\n", q19)

Original array:
 [5 4 3 2 1]
Interleaved array:
 [5 0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1]


**20. Consider an array of dimension (5, 5, 3), how to mulitply it element-wise by an array with dimensions (5, 5) - i.e., (5, 5, 0)$\times$(5, 5), (5, 5, 1)$\times$(5, 5), (5, 5, 2)$\times$(5, 5)**

In [170]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))

print("(5, 5, 0) x (5, 5) =\n", np.multiply(A[:, :, 0], B))
print("\n(5, 5, 1) x (5, 5) =\n", np.multiply(A[:, :, 1], B))
print("\n(5, 5, 2) x (5, 5) =\n", np.multiply(A[:, :, 2], B))


(5, 5, 0) x (5, 5) =
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

(5, 5, 1) x (5, 5) =
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

(5, 5, 2) x (5, 5) =
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


**21. Swap the first and second rows of the 2D array below**

In [ ]:
W = np.arange(30).reshape(6,5)
print(W)
print()
# Include your solution below


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    